
      - name: Save Updated Site
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git fetch origin main
          git reset --mixed origin main # Resets the robot to match the current state
          git add index.html
          git commit -m "Auto-update index.html" || exit 0
          git push origin main --force
